# OAuth2 소셜 로그인 설정 템플릿
# 실제 사용 시:
# 1. 이 파일을 복사해서 application-oauth-local.yml 생성
# 2. YOUR_XXX_HERE 부분을 실제 값으로 변경
spring:
  security:
    oauth2:
      client:
        registration:
          # 카카오 로그인 설정
          kakao:
            client-id: YOUR_KAKAO_CLIENT_ID_HERE
            client-secret: YOUR_KAKAO_CLIENT_SECRET_HERE
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
            client-name: Kakao

          # 네이버 로그인 설정
          naver:
            client-id: YOUR_NAVER_CLIENT_ID_HERE
            client-secret: YOUR_NAVER_CLIENT_SECRET_HERE
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - name
              - email
            client-name: Naver

        provider:
          # 카카오 OAuth2 Provider 설정
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          # 네이버 OAuth2 Provider 설정
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# 설정 가이드:
# 
# 1. 카카오 개발자 센터 (https://developers.kakao.com)
#    - 내 애플리케이션 > 앱 키 > REST API 키 → client-id
#    - 내 애플리케이션 > 보안 > Client Secret → client-secret
#    - 제품 설정 > 카카오 로그인 > Redirect URI 등록
#
# 2. 네이버 개발자 센터 (https://developers.naver.com)
#    - 내 애플리케이션 > Client ID → client-id
#    - 내 애플리케이션 > Client Secret → client-secret
#    - API 설정 > Callback URL 등록